### ISSUE TITLE
can you please checkin the corrected code. all versions have bugged version 

### ISSUE THREAD

**Issue by Maverick7** [inammathe/AppDynamics#12]
```
 Get-AppDMetricData -MetricPath "***%2FEngagementDocumentLibrary%7C%2FEngagementDocumentLibrary%2FViews" -AppName "***" | Out-Gri
dView
```

_Invoke-RestMethod : Error report HTTP Status 400 - Invalid application id 6 is specifiedtype Status reportmessageInvalid application id 6 is specifieddescriptionThe
request sent by the client was syntactically incorrect._

**Comment by inammathe** [comment]
Thanks @Maverick7, I must have left that in 6 hardcoded and forgot to substitute in the $AppId param.
I've just merged the fix, let me know if you have any issues :)
